// export const API_ROOT = 'https://around-75015.appspot.com/api/v1';
export const ORDER_NUM = 'ORDER_NUM';
export const SF_COORD = {lat: 37.773972, lng: -122.431297}
export const API_ROOT = 'http://ec2-54-205-150-119.compute-1.amazonaws.com/RoboticCourierSystem';
//export const API_ROOT = 'http://localhost:8080/RoboticCourierSystem'
// export const proxyurl = "https://cors-anywhere.herokuapp.com/";
export const TOKEN_KEY = 'TOKEN_KEY';
export const NUMBER = /[0-9]+/;
export const WORD = /[a-zA-Z]+[a-zA-Z\s]*[a-zA-Z]+/gi;
export const PRICE = /[0-9]+.[0-9]{2}/;
export const MAP_API_KEY ="AIzaSyB43agit7BDYyF6z6CdRuupfdeUMshOmbg";
//export const API_ROOT = 'https://around-75015.appspot.com/api/v1';
export const USER_ID = 'USER_ID';